num1 = int(input("შეიყვანეთ რიცხვი 1: "))
num2 = int(input("შეიყვანეთ რიცხვი 2: "))
num3 = int(input("შეიყვანეთ რიცხვი 3: "))
num4 = int(input("შეიყვანეთ რიცხვი 4: "))
num5 = int(input("შეიყვანეთ რიცხვი 5: "))

print(f"(num1 + num2) = {num1 + num2}")
print(f"num1 - num3 = {num1 - num3}")
print(f"num2 * num4 = {num2 * num4}")
print(f"num3 / num5 = {num3 / num5}")
print(f"num1 ** num2 = {num1 ** num2}")
print(f"num5 % num4 = {num5 % num4}")
print(f"num1 + num2 * num3 = {num1 + num2 * num3}")
print(f"(num4 + num5) / num1 = {(num4 + num5) / num1}")
print(f"(num2 * num3) - num5 = {(num2 * num3) - num5}")
print(f"num4 % (num1 + num2) = {num4 % (num1 + num2)}")