name = input ("name")
surname = input("surname")
age = int (input ("age"))
num1 = int (input ("number"))
num2 = int(input ("number2"))
print (num1  + num2)
print (name)
print ( surname)
print (age)
print (num1)
print (num2)
